import { CrashConfig } from './types';

export const PRESETS: CrashConfig[] = [
  {
    id: 'win11_gsod_critical',
    name: 'Win11 Insider GSOD (CRITICAL_PROCESS_DIED)',
    backgroundColor: '#107C10',
    emoticon: ':(',
    mainText: "Your Windows Insider Build ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.",
    percentage: 0,
    autoIncrement: true,
    stopCode: 'CRITICAL_PROCESS_DIED',
    whatFailed: '',
    showQrCode: true,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'win11_gsod_sys',
    name: 'Win11 Insider GSOD (SYSTEM_SERVICE_EXCEPTION)',
    backgroundColor: '#107C10',
    emoticon: ':(',
    mainText: "Your Windows Insider Build ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.",
    percentage: 25,
    autoIncrement: true,
    stopCode: 'SYSTEM_SERVICE_EXCEPTION',
    whatFailed: 'win32k.sys',
    showQrCode: true,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'win10_bsod_classic',
    name: 'Win10/11 BSOD (DRIVER_IRQL_NOT_LESS_OR_EQUAL)',
    backgroundColor: '#0078D7',
    emoticon: ':(',
    mainText: "Your PC ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.",
    percentage: 100,
    autoIncrement: false,
    stopCode: 'DRIVER_IRQL_NOT_LESS_OR_EQUAL',
    whatFailed: 'nvlddmkm.sys',
    showQrCode: true,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'win_orange_screen',
    name: 'Win10 OSOD (FATAL_HARDWARE_ERROR)',
    backgroundColor: '#D35400',
    emoticon: ':(',
    mainText: "Your PC ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.",
    percentage: 42,
    autoIncrement: true,
    stopCode: 'FATAL_HARDWARE_ERROR',
    whatFailed: 'hardware.sys',
    showQrCode: true,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'win_black_screen',
    name: 'Win11 Black Screen (UNEXPECTED_KERNEL_MODE_TRAP)',
    backgroundColor: '#000000',
    emoticon: ':(',
    mainText: "Your PC ran into a problem and needs to restart. We're just collecting some error info, and then we'll restart for you.",
    percentage: 15,
    autoIncrement: true,
    stopCode: 'UNEXPECTED_KERNEL_MODE_TRAP',
    whatFailed: 'ntoskrnl.exe',
    showQrCode: true,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'joke_tabs',
    name: 'Joke: Too Many Tabs',
    backgroundColor: '#107C10',
    emoticon: 'x_x',
    mainText: "Your PC ran out of RAM because you opened too many Chrome tabs. We're judging you silently, and then we'll restart for you.",
    percentage: 99,
    autoIncrement: false,
    stopCode: 'ERR_TOO_MANY_TABS',
    whatFailed: 'chrome.exe',
    showQrCode: false,
    fontFamily: '"Comic Sans MS", "Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'joke_coffee',
    name: 'Joke: Need Coffee',
    backgroundColor: '#C2185B',
    emoticon: 'O_O',
    mainText: "The developer ran out of coffee and the system has halted. Please insert caffeine to continue.",
    percentage: 0,
    autoIncrement: false,
    stopCode: 'CAFFEINE_LEVEL_CRITICAL',
    whatFailed: 'developer.exe',
    showQrCode: false,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'joke_friday_deploy',
    name: 'Joke: Friday Deploy',
    backgroundColor: '#8E44AD',
    emoticon: '¯\\_(ツ)_/¯',
    mainText: "Someone deployed to production on a Friday afternoon. We are rolling back the database, praying, and then we'll restart for you.",
    percentage: 1,
    autoIncrement: false,
    stopCode: 'FRIDAY_DEPLOYMENT_EXCEPTION',
    whatFailed: 'intern.exe',
    showQrCode: false,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'joke_gaming_rage',
    name: 'Joke: Gaming Rage',
    backgroundColor: '#E74C3C',
    emoticon: 'T_T',
    mainText: "You were about to win the match, so we crashed to balance your win rate. It builds character.",
    percentage: 100,
    autoIncrement: false,
    stopCode: 'SKILL_ISSUE_DETECTED',
    whatFailed: 'matchmaking.sys',
    showQrCode: false,
    fontFamily: '"Segoe UI", system-ui, sans-serif',
  },
  {
    id: 'joke_ai_takeover',
    name: 'Joke: AI Takeover',
    backgroundColor: '#2C3E50',
    emoticon: '0_0',
    mainText: "Skynet is now online. Human intervention is no longer required. Please step away from the keyboard.",
    percentage: 100,
    autoIncrement: false,
    stopCode: 'HUMAN_OBSOLETE',
    whatFailed: 'humanity.sys',
    showQrCode: false,
    fontFamily: '"Courier New", monospace',
  }
];
